%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContextExt_NotEmpty
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2015-12-17_21/otp_src_18/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContextExt_NotEmpty').
-ic_compiled("4_4").


-include("CosNaming_NamingContextExt.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/NotEmpty:1.0",
                   "NotEmpty",[]}.

%% returns id
id() -> "IDL:CosNaming/NamingContextExt/NotEmpty:1.0".

%% returns name
name() -> "CosNaming_NamingContextExt_NotEmpty".



