%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: StackModule_EmptyStack
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2015-12-17_21/otp_src_18/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('StackModule_EmptyStack').
-ic_compiled("4_4").


-include("StackModule.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:StackModule/EmptyStack:1.0","EmptyStack",[]}.

%% returns id
id() -> "IDL:StackModule/EmptyStack:1.0".

%% returns name
name() -> "StackModule_EmptyStack".



