%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: StackModule
%% Source: /net/isildur/ldisk/daily_build/18_prebuild_opu_o.2015-12-17_21/otp_src_18/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(STACKMODULE_HRL).
-define(STACKMODULE_HRL, true).


-record('StackModule_EmptyStack', {'OE_ID'="IDL:StackModule/EmptyStack:1.0"}).


-endif.


